language: python
os:
  - linux
  - windows

install:
  - pip install -r requirements.txt

script:
  - pyinstaller -F ipsdoc.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - dist/ispdoc
    - dist/ispdoc.exe
  skip_cleanup: true
  on:
    tags: true
    branch: master
