language: python

matrix:
  include:
    - name: "Windows"
      os: windows
      language: sh
      before_install:
        - choco install python3 --x86 --params "/InstallDir:C:\\python"
        - export PATH="/c/python:/c/python/scripts:$PATH"
      script:
        - pyinstaller -F ipsdoc.py
        - dist/ipsdoc.exe -h

    - name: "Linux"

install:
  - pip install -r requirements.txt

script:
  - pyinstaller -F ipsdoc.py

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - dist/ipsdoc
    - dist/ipsdoc.exe
  skip_cleanup: true
  on:
    tags: true
    branch: master
