name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and package
        run: |
          set -xeu -o pipefail
          pip install -r requirements.txt
          pyinstaller -F ipsdoc.py
        shell: bash

      - name: Upload artifacts - exe
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/') && (matrix.os == 'windows-latest')"
        with:
          name: ipsdoc.exe
          path: dist/ipsdoc.exe

      - name: Upload artifacts - linux bin
        uses: actions/upload-artifact@v2
        if: "!startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu-latest')"
        with:
          name: ipsdoc
          path: dist/ipsdoc

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/ipsdoc
            dist/ipsdoc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
